export default {

	GET_ITEMS:"GET_ITEMS",
	GET_ITEMS_PENDING:"GET_ITEMS_PENDING",
	GET_ITEMS_FULFILLED:"GET_ITEMS_FULFILLED",
	GET_ITEMS_REJECTED:"GET_ITEMS_REJECTED",

	DELETE_ITEM:"DELETE_ITEM",
	DELETE_ITEM_PENDING:"DELETE_ITEM_PENDING",
	DELETE_ITEM_FULFILLED:"DELETE_ITEM_FULFILLED",
	DELETE_ITEM_REJECTED:"DELETE_ITEM_REJECTED",

	EDIT_ITEM:"EDIT_ITEM",
	EDIT_ITEM_PENDING:"EDIT_ITEM_PENDING",
	EDIT_ITEM_FULFILLED:"EDIT_ITEM_FULFILLED",
	EDIT_ITEM_REJECTED:"EDIT_ITEM_REJECTED",

	ADD_ITEM:"ADD_ITEM",
	ADD_ITEM_PENDING:"ADD_ITEM_PENDING",
	ADD_ITEM_FULFILLED:"ADD_ITEM_FULFILLED",
	ADD_ITEM_REJECTED:"ADD_ITEM_REJECTED",

	ADD_ITEM_CART:"ADD_ITEM_CART",
	ADD_ITEM_CART_PENDING:"ADD_ITEM_CART_PENDING",
	ADD_ITEM_CART_FULFILLED:"ADD_ITEM_CART_FULFILLED",
	ADD_ITEM_CART_REJECTED:"ADD_ITEM_CART_REJECTED",

	DELETE_ITEM_CART:"DELETE_ITEM_CART",
	DELETE_ITEM_CART_PENDING:"DELETE_ITEM_CART_PENDING",
	DELETE_ITEM_CART_FULFILLED:"DELETE_ITEM_CART_FULFILLED",
	DELETE_ITEM_CART_REJECTED:"DELETE_ITEM_CART_REJECTED",

	SEARCH_ITEMS:"SEARCH_ITEMS";

}
